name: Build Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x  # 按您的项目需要选择适当的版本

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish binary
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: binary-artifact
        path: ./publish
